name: 'The-GhostRiderGitHubActions-issue-labeler'
description: 'Issue labeler for GR-PRJ_AzerothCore-Wotlk2.0 Repository'
author: 'The-GhostRider'
inputs:
  token:
    description: 'GitHub token with access to the repository'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
